// ======================================================
// COMPETITION ANALOG PID LINE FOLLOWER
// OPTIMIZED FOR:
// White ≈ 50
// Black ≈ 200–500
// ======================================================

#include <math.h>

#define ADD_INITIAL_DELAY 0
#define PRINT_DEBUG_OUTPUT 1
#define PRINT_OTHER_DEBUG_OUTPUT 1
#define PRINT_MOTOR_DEBUG_OUTPUT 1

#define COMPENSATE_FOR_MOTOR_GEAR_FRICTION 0

// ---------------- SENSOR PINS ----------------
// Analog pins
#define SENSOR_LEFT    A0
#define SENSOR_CENTER  A1
#define SENSOR_RIGHT   A2

// Digital pins
#define DIGITAL_SENSOR_LEFT    2
#define DIGITAL_SENSOR_CENTER  3
#define DIGITAL_SENSOR_RIGHT   4

// ---------------- MOTOR PINS -----------------

// LEFT MOTOR
#define ENA 5
#define IN1 6
#define IN2 7
// To drive left motor forward, IN1 needs to be HIGH, and IN2 needs to be LOW (for my wiring)

// RIGHT MOTOR
#define ENB 9
// Note: the wiring diagram provided for the competition has these swapped (IN3->10, IN4->11)
// For me I have them wired up this way to match code currently being generated by AI (GPT)
#define IN3 10
#define IN4 11
// To drive the Right motor forward you need to drive IN3 LOW and IN4 HIGH (for my wiring)

// ======================================================
// PID SETTINGS
// ======================================================

// Tuned for higher speed stability
float Kp = 0.11;  // initial suggested default 0.085  // reduce this value if oscillation (left/right)/wobble occurs.  // increase this if the robot reacts too slowly (is too sluggish)
float Ki = 0.0000;
float Kd = 1.80;  // initial suggested default 1.25  // increase this if oscillation (left/right)/wobble occurs

// very initial intentional conservative numbers
//float Kp = 35.0;
//float Ki = 0.0;
//float Kd = 18.0;

// PID variables
float error = 0;
float previousError = 0;
float integral = 0;
float derivative = 0;
float correction = 0;

// ======================================================
// SPEED SETTINGS
// ======================================================

// Competition speed
//int baseSpeed = 140; //120; //160; //205;  // 180 is conservative.
int baseSpeed = 180; //120; //160; //205;  // 180 is conservative.


// Maximum PWM
int maxSpeed = 255;

// Recovery speed
//int searchSpeed = 100; //80; //80; //110; //140;  // 110 is too slow for our motors.
int searchSpeed = 110; //80; //80; //110; //140;  // 110 is too slow for our motors.

// ======================================================
// SENSOR CALIBRATION
// ======================================================

// Your observed values:
//
// WHITE ≈ 50
// BLACK ≈ 200–500
//

// These are the analog values as read by the IR sensors over a white surface and over a black electrical tape surface.
//int whiteValue = 50;
int whiteValue = 35;
int blackValue = 500;

// Ignore weak noise below this
int detectionThreshold = 80;

// ======================================================
// TRACKING VARIABLES
// ======================================================

// Negative values are to the left, 0 is center, and positive values are to the right.
float lastKnownPosition = 0;

bool runInitialDelay = true;

bool loopSequenceDone = false;

int lastLeftMotorSpeed = 0;
int lastRightMotorSpeed = 0;

// ======================================================
// SETUP
// ======================================================

void setup() 
{
  Serial.begin(115200);

  // Motor pins
  pinMode(ENA, OUTPUT);
  pinMode(IN1, OUTPUT);
  pinMode(IN2, OUTPUT);

  pinMode(ENB, OUTPUT);
  pinMode(IN3, OUTPUT);
  pinMode(IN4, OUTPUT);

  stopMotors();

  pinMode(LED_BUILTIN, OUTPUT);

  // Startup sequence: 500 ms intervals
  digitalWrite(LED_BUILTIN, HIGH);
  delay(500);

  digitalWrite(LED_BUILTIN, LOW);
  delay(500);

  digitalWrite(LED_BUILTIN, HIGH);
  delay(500);

  digitalWrite(LED_BUILTIN, LOW);
  delay(500);

  Serial.println("COMPETITION PID LINE FOLLOWER");
}

// ======================================================
// MAIN LOOP
// ======================================================

void loop() 
{

//  fastBlinkLed();

  if (!loopSequenceDone) {

    // Loop sequence: 250 ms intervals
    digitalWrite(LED_BUILTIN, HIGH);
    delay(250);

    digitalWrite(LED_BUILTIN, LOW);
    delay(250);

    digitalWrite(LED_BUILTIN, HIGH);
    delay(250);

    digitalWrite(LED_BUILTIN, LOW);
    delay(250);

    loopSequenceDone = true;  // Prevent running again
  }

#if ADD_INITIAL_DELAY
  if(runInitialDelay == true)
  {
    // Delay 3 seconds
    Serial.println("Performing startup delay.");
    delay(3000);
    runInitialDelay = false;
    Serial.println("Completed startup delay.");
  }
#endif

  // --------------------------------------------------
  // READ RAW SENSOR VALUES
  // --------------------------------------------------

  int rawLeft   = analogRead(SENSOR_LEFT);
  int rawCenter = analogRead(SENSOR_CENTER);
  int rawRight  = analogRead(SENSOR_RIGHT);

  // --------------------------------------------------
  // NORMALIZE SENSOR VALUES
  // --------------------------------------------------

  int leftValue   = normalizeSensor(rawLeft);
  int centerValue = normalizeSensor(rawCenter);
  int rightValue  = normalizeSensor(rawRight);

  // --------------------------------------------------
  // LINE DETECTION
  // --------------------------------------------------

  long total =
      leftValue +
      centerValue +
      rightValue;

  // --------------------------------------------------
  // LOST LINE CONDITION
  // --------------------------------------------------

  if (total < detectionThreshold) 
  {
    // adding additional recommended code from ChatGPT
    // reset PID state on line loss
    integral = 0;
    previousError = error;

    // if the last known position was to the left (negative), search to the left
    if (lastKnownPosition < 0) 
    {
      searchLeft();
    }
    else 
    {
      searchRight();
    }

    debugOutput(
      rawLeft,
      rawCenter,
      rawRight,
      leftValue,
      centerValue,
      rightValue
    );

    return;  // this is against coding standard.    haha!!!
  }

  // --------------------------------------------------
  // WEIGHTED POSITION CALCULATION
  // --------------------------------------------------

//  long weightedSum =
//      ((long)leftValue * -1000L) +
//      ((long)centerValue * 0L) +
//      ((long)rightValue * 1000L);
  long weightedSum =
      ((long)leftValue * 1000L) +
      ((long)centerValue * 0L) +
      ((long)rightValue * -1000L);

  if(total == 0)
  {
    fastBlinkLed();
  }


  error = (float)weightedSum / total;

  lastKnownPosition = error;

  // --------------------------------------------------
  // PID CALCULATIONS
  // --------------------------------------------------

  integral += error;

  // Anti-windup
  integral = constrain(integral, -3000, 3000);

  derivative = error - previousError;

  correction =
      (Kp * error) +
      (Ki * integral) +
      (Kd * derivative);

  previousError = error;

  // --------------------------------------------------
  // DYNAMIC SPEED REDUCTION
  // Slow slightly in sharp turns
  // --------------------------------------------------

//  int speedReduction =
//      min(abs(error) / 6, 60);
int speedReduction =
    min((int)(fabs(error) / 6.0), 60);

  int adjustedBaseSpeed =
      baseSpeed - speedReduction;

  // --------------------------------------------------
  // MOTOR SPEEDS
  // --------------------------------------------------

  int leftMotorSpeed =
      adjustedBaseSpeed + correction;

  int rightMotorSpeed =
      adjustedBaseSpeed - correction;

  leftMotorSpeed =
      constrain(leftMotorSpeed, 0, maxSpeed);

  rightMotorSpeed =
      constrain(rightMotorSpeed, 0, maxSpeed);

  // --------------------------------------------------
  // DRIVE MOTORS
  // --------------------------------------------------

  setMotorSpeed(
      leftMotorSpeed,
      rightMotorSpeed
  );

  // --------------------------------------------------
  // DEBUG OUTPUT
  // --------------------------------------------------

  debugOutput(
      rawLeft,
      rawCenter,
      rawRight,
      leftValue,
      centerValue,
      rightValue
  );

  // FAST LOOP
  delayMicroseconds(1200);
}

// ======================================================
// SENSOR NORMALIZATION
// ======================================================

int normalizeSensor(int rawValue) 
{
  // Clamp to calibration range
  rawValue = constrain(
      rawValue,
      whiteValue,
      blackValue
  );

  // Convert to 0-1000 scale
  int normalized =
      map(
          rawValue,
          whiteValue,
          blackValue,
          0,
          1000
      );

  // Remove weak noise
  if (normalized < 30) 
  {
    normalized = 0;
  }

  return normalized;
}

void driveMotors(
    int leftSpeed,
    int rightSpeed
) 
{

#if COMPENSATE_FOR_MOTOR_GEAR_FRICTION
  // Need to pulse the motors to help overcome internal friction
  analogWrite(ENA, maxSpeed);
  analogWrite(ENB, maxSpeed);
  //delay(1);
  delayMicroseconds(1000);  // 500 is barely enough
#endif

  // for debugging motor speed
  lastLeftMotorSpeed = leftSpeed;
  lastRightMotorSpeed = rightSpeed;
  analogWrite(ENA, leftSpeed);
  analogWrite(ENB, rightSpeed);
}

// ======================================================
// MOTOR CONTROL
// ======================================================

void setMotorSpeed(
    int leftSpeed,
    int rightSpeed
) 
{
  // LEFT MOTOR FORWARD
  digitalWrite(IN1, HIGH);
  digitalWrite(IN2, LOW);

  // RIGHT MOTOR FORWARD
  digitalWrite(IN3, LOW); // HIGH);
  digitalWrite(IN4, HIGH); //LOW);

  //analogWrite(ENA, leftSpeed);
  //analogWrite(ENB, rightSpeed);
  driveMotors(leftSpeed, rightSpeed);

}

// ======================================================
// STOP
// ======================================================

void stopMotors() 
{
  analogWrite(ENA, 0);
  analogWrite(ENB, 0);
}

// ======================================================
// SEARCH LEFT
// ======================================================

void searchLeft() 
{
#if PRINT_DEBUG_OUTPUT
//  Serial.println("Search left.");
#endif

  // Left tire needs to go in reverse
  digitalWrite(IN1, LOW);
  digitalWrite(IN2, HIGH);

  // Right tire needs to go forward
  digitalWrite(IN3, LOW); //HIGH); // compensating for my wiring.
  digitalWrite(IN4, HIGH); //LOW); // compensating for my wiring.

  //analogWrite(ENA, searchSpeed);
  //analogWrite(ENB, searchSpeed);
  driveMotors(searchSpeed, searchSpeed);
}

// ======================================================
// SEARCH RIGHT
// ======================================================

void searchRight() 
{
#if PRINT_DEBUG_OUTPUT
//  Serial.println("Search right.");
#endif

  // Left tire needs to go forward
  digitalWrite(IN1, HIGH);
  digitalWrite(IN2, LOW);

  // Right tire needs to go in reverse
  digitalWrite(IN3, HIGH);
  digitalWrite(IN4, LOW);

  //analogWrite(ENA, searchSpeed);
  //analogWrite(ENB, searchSpeed);
  driveMotors(searchSpeed, searchSpeed);
}

// ======================================================
// DEBUG OUTPUT
// ======================================================

void debugOutput(
    int rawLeft,
    int rawCenter,
    int rawRight,
    int normLeft,
    int normCenter,
    int normRight
) 
{
static uint32_t lastPrint = 0;

if (millis() - lastPrint > 100)
{
    lastPrint = millis();


#if PRINT_DEBUG_OUTPUT
#if PRINT_OTHER_DEBUG_OUTPUT

  Serial.print("RAW: ");

  Serial.print(rawLeft);
  Serial.print(" ");

  Serial.print(rawCenter);
  Serial.print(" ");

  Serial.print(rawRight);

  Serial.print(" | NORM: ");

  Serial.print(normLeft);
  Serial.print(" ");

  Serial.print(normCenter);
  Serial.print(" ");

  Serial.print(normRight);

  Serial.print(" | ERR: ");
  Serial.print(error);

  Serial.print(" | CORR: ");
  Serial.print(correction);
#endif

#if PRINT_MOTOR_DEBUG_OUTPUT
  Serial.print(" | LLMS: ");
  Serial.print(lastLeftMotorSpeed);
  Serial.print(" | LRMS: ");
  Serial.print(lastRightMotorSpeed);
#endif

  Serial.println();
  #endif

  }

}

void fastBlinkLed()
{
  while(1)
  {
    digitalWrite(LED_BUILTIN, HIGH);
    delay(100);
    digitalWrite(LED_BUILTIN, LOW);
    delay(100);
  }

}

